# Generated by Django 5.2 on 2025-04-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EPP', 'Equipo de Protección'), ('REC', 'Recibo de Sueldo'), ('ANT', 'Antecedentes Penales')], max_length=3)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_vencimiento', models.DateField()),
                ('validado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.empleado')),
            ],
        ),
    ]
